###Get public content
http://localhost:8080/api/test/all

### Create roles
POST http://localhost:8080/api/auth/create-roles

### Get public content from aws
http://auth-LoadBa-CE6WE9PBOLD-581ae565c17c9e44.elb.us-east-1.amazonaws.com:8080/api/test/all

### Sign up
POST http://localhost:8080/api/auth/signup
content-type: application/json

{
    "username": "fa-1",
    "email": "fa-1@example.com",
    "password": "abc123",
    "role": ["fullaccess"]
}

### Sign up from aws
POST http://auth-LoadBa-CE6WE9PBOLD-581ae565c17c9e44.elb.us-east-1.amazonaws.com:8080/api/auth/signup
content-type: application/json

{
    "username": "fa-1",
    "email": "fa-1@example.com",
    "password": "abc123",
    "role": ["fullaccess"]
}

### Login
POST http://localhost:8080/api/auth/signin
content-type: application/json

{
    "username": "fa-1",
    "password": "abc123"
}

### Login
POST http://localhost:8080/api/auth/signin
content-type: application/json

{
    "username": "fa-1",
    "password": "abc123"
}

### Get user content
http://localhost:8080/api/test/user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmYS0xIiwiaWF0IjoxNjQ1MzIyNjIzLCJleHAiOjE2NDU0MDkwMjN9.lOBobAAom2D2OM5hUP9nAXiUt86cR-fU4c0QD7610TilswliV8pI_5Kiu5zh9y-pm7wRfNDITAZ8pPWAOL-lNg

### Get cardholder content
http://localhost:8080/api/test/cardholder
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmYS0xIiwiaWF0IjoxNjQ1MzIyNjIzLCJleHAiOjE2NDU0MDkwMjN9.lOBobAAom2D2OM5hUP9nAXiUt86cR-fU4c0QD7610TilswliV8pI_5Kiu5zh9y-pm7wRfNDITAZ8pPWAOL-lNg

### Get fullaccess content
http://localhost:8080/api/test/fullaccess
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmYS0xIiwiaWF0IjoxNjQ1MzIyNjIzLCJleHAiOjE2NDU0MDkwMjN9.lOBobAAom2D2OM5hUP9nAXiUt86cR-fU4c0QD7610TilswliV8pI_5Kiu5zh9y-pm7wRfNDITAZ8pPWAOL-lNg
