INSERT INTO roles(name) VALUES('ROLE_VIEWONLY') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('ROLE_FULLACCESS') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('ROLE_CARDHOLDER') ON CONFLICT DO NOTHING;